# Generated by Django 5.1.5 on 2025-02-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('amount', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
